steps:
    - name: gcr.io/cloud-builders/gcloud
      entrypoint: "bash"
      args:
          [
              "-c",
              "gcloud secrets versions access latest --secret=impesa-npmrc --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .npmrc",
          ]
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/test-ip:latest", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/test-ip:latest"]
